# after-startup-command = ['exec-and-forget sketchybar']
# exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE', 'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0']

start-at-login = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

accordion-padding = 300

# tiles|accordion
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

automatically-unhide-macos-hidden-apps = true


[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'layout floating'

[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run = ["layout tiling"]

# [key-mapping]
# preset = 'colemak'
#
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[mode.main.binding]
    alt-f = 'fullscreen'
		alt-z = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-space = 'layout floating tiling'
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

		alt-g = 'exec-and-forget open -n /Applications/Ghostty.app'
		alt-b = 'exec-and-forget open -n /Applications/Firefox.app'

		# alt-q = 'close' # instead use cmd + w

    alt-m = 'focus left'
    alt-n = 'focus down'
    alt-e = 'focus up'
    alt-i = 'focus right'

    alt-shift-m = 'move left'
    alt-shift-n = 'move down'
    alt-shift-e = 'move up'
    alt-shift-i = 'move right'

    alt-shift-left = 'join-with left'
    alt-shift-down = 'join-with right'
    alt-shift-up = 'join-with down'
    alt-shift-right = 'join-with up'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'

    alt-s = 'mode resize'
		alt-q = 'mode qwerty'

[mode.resize.binding]
    m = 'resize width -50'
    n = 'resize height +50'
    e = 'resize height -50'
    i = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[mode.qwerty.binding]
    alt-f = 'fullscreen'
		alt-z = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-space = 'layout floating tiling'
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

		alt-g = 'exec-and-forget open -n /Applications/Ghostty.app'
		alt-b = 'exec-and-forget open -n /Applications/Firefox.app'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-shift-left = 'join-with left'
    alt-shift-down = 'join-with right'
    alt-shift-up = 'join-with down'
    alt-shift-right = 'join-with up'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-shift-c = 'reload-config'

    alt-s = 'mode resizeq'
    alt-q = 'mode main'

[mode.resizeq.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode qwerty'
    esc = 'mode qwerty'
